In [8]:
import pandas as pd

df = pd.read_parquet("data/market_data.parquet")
df.head(5)

,date,symbol,open,high,low,close,adj_close,volume
0,2021-03-08,ADANIENT.NS,918.099976,926.400024,905.099976,910.200012,907.994446,3904469
1,2021-03-09,ADANIENT.NS,918.000000,928.400024,893.599976,905.200012,903.006531,5561849
2,2021-03-10,ADANIENT.NS,911.000000,914.099976,888.700012,898.150024,895.973633,5465016
3,2021-03-12,ADANIENT.NS,905.000000,923.799988,889.299988,894.099976,891.933411,6049852
4,2021-03-15,ADANIENT.NS,898.750000,904.000000,874.500000,896.200012,894.028442,5234540

In [9]:
df.columns

Index(['date', 'symbol', 'open', 'high', 'low', 'close', 'adj_close',
       'volume'],
      dtype='str')

In [10]:
df_2 = pd.read_parquet("data/signals.parquet")
df_2.head(5)

,date,symbol,open,high,low,close,adj_close,volume,history_bars,eligible,...,mom_126_raw,momentum_raw,reversal_raw,volatility_raw,trend_raw,momentum_score,reversal_score,volatility_score,trend_score,composite_score
0,2021-03-08,ADANIENT.NS,918.099976,926.400024,905.099976,910.200012,907.994446,3904469,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-09,ADANIENT.NS,918.000000,928.400024,893.599976,905.200012,903.006531,5561849,2,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-10,ADANIENT.NS,911.000000,914.099976,888.700012,898.150024,895.973633,5465016,3,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-12,ADANIENT.NS,905.000000,923.799988,889.299988,894.099976,891.933411,6049852,4,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-15,ADANIENT.NS,898.750000,904.000000,874.500000,896.200012,894.028442,5234540,5,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN